### ISSUE TITLE
Add Technical Documentation and Appendix PDFs as files to FrEDI repo

### ISSUE THREAD

**Issue by emcduffie** [USEPA/FrEDI#207]
1) Add the PDFs of the latest peer-reviewed version of TD and Appendix to the package repo and/or
2) Add links to the TD and Appendix to the 'sidebar' of the FrEDI IO page, by adding the following code to the pkgdown.yml file and then re-building the site:
```
home:
  links:
  - text: FrEDI Technical Documentation
    href: https://www.epa.gov/system/files/documents/2024-08/technical-documentation-for-fredi_aug2024.pdf
  - text: FrEDI Technical Documentation Appendix 
    href: https://www.epa.gov/system/files/documents/2024-08/technical-documentation-for-fredi_appendices_aug2024.pdf
```

[more info on the side bar here: https://pkgdown.r-lib.org/reference/build_home.html]
